cash_flow_dict = {
    'in' : ['Cash Contribution',
            'In-Kind Contribution',
            'Pledge of Cash',
            'Loan Received (Non-Exempt)',
            'In-Kind/Forgiven Personal Expenditures',
            'In-Kind/Forgiven Account Payable',
            'Pledge of In-Kind',
            'Pledge of Loan',
            'Items Sold at Fair Market Value',
            'Interest/Investment Income',
            'Loan Received (Exempt)',
            'Loan Forgiven (Non-Exempt)',
            'Unexpended Agent Balance',
            'Cash Balance Adjustment',
            'Account Payable Rescinded',
            'Miscellaneous Account Receivable'],
    'out' : ['Cash Expenditure',
             'Personal Expenditure for Reimbursement',
             'Account Payable',
             'Expenditure Made by an Agent',
             'Loan Payment (Non-Exempt)',
             'Lost or Returned Check',
             'Refunds and Rebates',
             'Miscellaneous Other Receipt',
             'Miscellaneous Other Disbursement',
             'Loan Payment (Exempt)',
             'Uncollectible Pledge of Cash',
             'Personal Expenditure Balance Adjustment',
             'Return or Refund of Contribution',
             'Nonpartisan Activity']
}